# Generated by Django 4.0.5 on 2022-07-05 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='isBlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signup',
            name='lastLoginAttemptedTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 5, 13, 37, 14, 561922)),
        ),
        migrations.AddField(
            model_name='signup',
            name='loginAttempt',
            field=models.IntegerField(default=0),
        ),
    ]
